Dockerfile, README.md, run/gunicorn/run.py, wsgi.py
=> BAU: add dockerfile

app/__init__.py, config/envs/default.py, config/envs/development.py, config/envs/unit_test.py, pyproject.toml, setup.cfg
Take linting rules from data-store for consistency (allow 120 character lines)
=> BAU: add linting rules from data-store

app/static/src/css/custom.css, app/templates/main/upload.html
Updates upload page to match design at: https://www.figma.com/file/eU00tDFeRbGx4PCN1uFBHW/%2F%2F-Submit-%2F%2F-October-2023-TF-Deliverable?type=design&node-id=188-1953&mode=design&t=wo5ZafhWzLrHz4Fl-0
=> [BAU]: update upload page

app/main/routes.py, tests/test_routes.py
...
Fixed the wording for status/status_code to be consistent throughout the project. We use status everywhere else so need to use it here as well
=> BAU: fixed inconsistent status_code convention

app/main/data_requests.py, app/main/routes.py, tests/test_routes.py
Align front-end with validation errors being returned with 440 HTTP status code.
=> [SMD-5] align backend on 440 HTTP status code for validation errors

app/main/routes.py
Switches from expecting Round 3 to Round 4 submissions.
=> [BAU] switch to expecting Round 4 submissions

app/main/data_requests.py, app/main/routes.py, app/templates/main/500.html, tests/test_routes.py
- Validation Error status code 440 -> 400
- Adds test case that covers handling a generic 400 response
=> [BAU] revert validation error status code from 440 to 400

copilot/.workspace, copilot/submit/manifest.yml
Adds Copilot manifests
Have tested deployment is successful on branch: https://github.com/communitiesuk/funding-service-design-post-award-submit/actions/runs/6158634572 (N.B. URL won't be functional until additional DNS records have been added)
=> SMD-18: Add Copilot manifests

app/__init__.py, config/envs/default.py
- Fixes an issue where an AttributeError is raised on the test environment due to no additional email mapping on the default config. This change retrieves it from the app config instead, with a default value if it's not present.
- Adds developer email domains to the default config so that we can submit on the Test environment - to be replaced with an envar lookup in upcoming ticket.
=> [FIX] email mapping instantiation

app/templates/main/upload.html
https://dluhcdigital.atlassian.net/jira/software/c/projects/SMD/boards/140?modal=detail&selectedIssue=SMD-184&quickFilter=815
Changes wording of 'upload CSV' to 'upload an Excel file'. The change should be visible in the UI.
=> SMD-184 fix wording on upload prompt

.github/workflows/deploy.yml, copilot/submit/manifest.yml
Adds required stuff to deploy on test environment
Have tested on branch and deploy was successful: https://github.com/communitiesuk/funding-service-design-post-award-submit/actions/runs/6264063750/job/17009894087
=> SMD-55: Deployment workflow and basic auth sidecar

app/main/routes.py
- aligns with refactoring branch on data-store
=> [BAU] correct ingest params inline with data-store changes

app/const.py, tests/test_authorisation.py
Updated e-mail domains as per https://dluhcdigital.atlassian.net/browse/SMD-210
Also added an additional test for one of the updated e-mail domains
=> [SMD-210]: update email domains

app/main/data_requests.py, app/main/routes.py, tests/test_routes.py
https://dluhcdigital.atlassian.net/browse/SMD-189
- refactor that moves handling logic of the ingest response out of `routes.py`
- logs the failure ID in the case of an unknown ingest error
This ID will allow us to identify which file caused this error, along with the users details via sentry. We will then be able to retrieved the relevant file from S3 and begin communication with the user with how to proceed. 
=> SMD-189 log unknown failure

.github/workflows/deploy.yml
We want more control over deployments to turning off automatic deployment of the main branch
Should not deploy on merge
=> BAU: remove automatic deployment of main branch

.github/workflows/deploy.yml
Adds a separate dev environment. Note implementation is slightly hacky as the copilot environments are named the same in both AWS accounts, so we have to inject the correct values to differentiate between them.
Have tested deployment works on this branch: https://github.com/communitiesuk/funding-service-design-post-award-submit/actions/runs/6481528309/job/17599220782
=> FMD-21: add dev environment

.github/workflows/deploy.yml
Reverts communitiesuk/funding-service-design-post-award-submit#35
=> Revert "BAU: remove automatic deployment of main branch"

app/templates/main/login.html
https://dluhcdigital.atlassian.net/jira/software/c/projects/SMD/boards/140?quickFilter=815&selectedIssue=SMD-230
Content changes on the sign-in page, they should all be congruent with the designs in the ticket.
=> smd-230 update copy on landing page

app/main/routes.py, app/templates/main/upload.html, config/envs/default.py, tests/test_routes.py
https://dluhcdigital.atlassian.net/jira/software/c/projects/SMD/boards/140?quickFilter=815&selectedIssue=SMD-231
Updates the copy displayed in different scenarios for the due date.
Due in more than several days:
Due tomorrow:
Due today:
Overdue:
The environment variable SUBMIT_DEADLINE can be changed on line 33 of the file config/envs/default.py (when testing locally).
=> Smd-231-update-upload-screen

.github/workflows/deploy.yml
=> BAU: Disable continuous deployment

app/main/notify.py
- one line fix to correct a dictionary lookup
=> [BAU] fix metadata lookup

app/main/routes.py, app/templates/main/errorSummary.html, app/templates/main/upload.html, tests/test_routes.py
Changed the presentation of pre-validation messages to use error summary component and bulleted lists of error messages.
=> [SMD-324] Front end pre-validation summary changes

app/templates/base.html, app/templates/main/upload.html
https://dluhcdigital.atlassian.net/wiki/spaces/FS/pages/50561200/Design+Team+testing
- fix sign out button content
- fixes upload page width
- fixes content around re-uploading on error page
=> [BAU] fixes from design testing

config/envs/default.py
- updates the default deadline date to the actual deadline date 
- [] README and other documentation has been updated / added (if needed)
=> [BAU] update deadline date default

app/templates/main/login.html, app/templates/main/upload.html, tests/test_routes.py
https://dluhcdigital.atlassian.net/browse/SMD-340
- updates sign in page content
- fixes the deadline notification banner to only display if deadline is 7 or fewer days away
=> [SMD-340] sign in page content

.github/workflows/deploy.yml
Reverts communitiesuk/funding-service-design-post-award-submit#48
=> Revert "BAU: Disable continuous deployment"

app/templates/main/upload.html
- fixes a bug where an empty notification banner was shown if days to the deadline was over a week
=> [BAU] fix notification banner

copilot/submit/manifest.yml
Adds production config overrides
Should deploy to production
=> SMD-208: add production config

app/const.py
Some users are still under this domain so need to add to safelist
Will confirm with user after deployment
=> BAU: Add hambleton to safelist

app/main/data_requests.py, config/envs/default.py, copilot/submit/manifest.yml
- removes DISABLE_LOAD as a secret
- instead just set in the copilot manifest 
=> [BAU] remove DISABLE_LOAD as secret

copilot/submit/manifest.yml
- disable DISABLE_LOAD on test
- enable DISABLE_LOAD on prod
=> [BAU] set DISABLE_LOAD to True on prod

app/templates/main/login.html
Login page tweaks, see slack thread: https://communities-govuk.slack.com/archives/C05KKACJKC4/p1698848600365479?thread_ts=1698846255.977259&cid=C05KKACJKC4
See screenshot below
=> BAU: tweak login page

Dockerfile
Make container more secure by running process as a non-root user
App should run as before if run e.g. via docker runner
=> SMD-331: run container as non-root user

Dockerfile
Reverts communitiesuk/funding-service-design-post-award-submit#54
=> Revert "SMD-331: run container as non-root user"

app/templates/main/help-links.html, tests/test_routes.py
Change need help titile Service Desk to Service desk (sentance case)
add govuk-link class to all need help links so that they are formated correctly
=> [SMD-353] content and formating changes for if you need help links

copilot/submit/manifest.yml
- re-enabled load in production now that the additional validation checks are implemented
- [] README and other documentation has been updated / added (if needed)
=> [BAU] re-enable load in production

.github/workflows/deploy.yml
- ensures tagging is consistent between jobs
=> [BAU] update tag version generation to be unified

build.py
Fix build file so that it can locate GDS font assets at run time and display correct font on page
=> [SMD-385] fix text not rendering as GDS transport

app/templates/main/login.html
https://dluhcdigital.atlassian.net/browse/SMD-360
- fixes the width of the help links dropdown
=> [SMD-360] fix sign in page help links width

app/main/data_requests.py, app/main/routes.py, tests/test_routes.py
This change came out of [this Sentry error](https://funding-service-design-team-dl.sentry.io/issues/4570964804/?alert_rule_id=14767746&alert_type=issue&notification_uuid=03a35327-1a26-4703-88ec-6cd3b7ff05ba&project=4505884669509632&referrer=slack). 
- Add server-side validation to check if a file has been uploaded
- Reword errors with improved content from the design team
=> [BAU] improve basic file validation on uploaded submission

.github/workflows/deploy.yml
Previously the jobs were running in parallel which meant the deployment was happening before the new package was published. This makes the deployment dependent on package completing, so things will happen sequentially
Have tested on dev https://github.com/communitiesuk/funding-service-design-post-award-submit/actions/runs/6876305385
=> BAU: add dependency on package step

app/const.py
Needed to resolve support ticket, users are linked to this domain.
Will check with user post-deployment
=> BAU: allow scarborough.gov.uk to submit for same places as northyorks

app/const.py
- Adds Commercial Road to `portsmouthcc.gov.uk` domain
=> [BAU] correct Portsmouth place auth

app/const.py
- adds cannock domain authed to submit for Ashfield Councils places
=> [BAU] adding cannock to the domain auth mapping

app/main/data_requests.py
- small change to improve handling of error when the application cannot connect to data-store
- [] README and other documentation has been updated / added (if needed)
=> [BAU] improve exception handling and logging when posting to /ingest

copilot/submit/manifest.yml
Enable validation error logging during busy period to gather some data for analysis
- enables system logging of all validation errors
=> [BAU] enable validation logging in prod via env var

.github/workflows/deploy.yml
- use latest version of Copilot when deploying via GitHub Actions
=> [BAU] use latest version of Copilot when deploying

app/main/routes.py
- logs the user along with submission metadata on successful submission
- this will then allow us to work out who submits for where and if anyone submits for multiple places from the logs
=> [BAU] log user on successful submission

app/main/decorators.py, app/main/routes.py, app/templates/main/upload.html, config/envs/unit_test.py, tests/test_routes.py
- converts auth check to a decorator 
- decorates the upload view with the new auth decorator
- injects the organisations associated with the user directly into the template via request context
=> [BAU] improve authorisation

.github/workflows/deploy.yml, copilot/submit/manifest.yml
Following the rebuilding of the dev environment we no longer need these overrides in the Github Action as the environments are more consistent
Have tested on dev environment
=> FMD-194: remove unneeded overrides

README.md
Fix formatting issue with `README.md` which made some text appear inside a code block, and some code appear as text. Also minor tweaks to things like capitalisation.
No testing required.
N/A
=> Fix code block formatting and minor tweaks elsewhere inc. to capitalisation

app/main/decorators.py, app/main/fund.py, app/main/routes.py, app/templates/main/dashboard.html, app/templates/main/select-fund.html, app/templates/main/upload.html, app/templates/main/uploadTable.html, app/templates/main/validation-errors.html, config/envs/development.py, config/envs/unit_test.py, tests/conftest.py, tests/test_fund.py, tests/test_routes.py
https://dluhcdigital.atlassian.net/browse/SMD-648 and https://dluhcdigital.atlassian.net/jira/software/c/projects/SMD/boards/140?quickFilter=815&selectedIssue=SMD-648
Both the tickets are combined into one, as the front end changes are needed for the auth changes to work properly. Additional confirmation is needed on the specific front-end elements used for the new /select-fund page.
- [] README and other documentation has been updated / added (if needed)
=> [SMD-646] add fund code to Auth and add coded routes

app/main/fund.py, app/main/routes.py
N/A
Small tweaks to Submit ahead of demo to LAs on test environment on Thursday, including:
- Making reporting period accurate
- Adding reporting round deadline date (confirmed with PF in hotline)
- Adding missing reporting period to HTML table displayed on upload page in case of validation errors
=> BAU - Submit demo tweaks

app/templates/main/login.html
Remove create an account block
Create an account block should not be visible on login page./
=> SMD-698: remove create an account block

app/main/fund.py, config/envs/default.py, config/envs/development.py, copilot/submit/manifest.yml, tests/test_routes.py
Update Fund config for Towns Fund round 5 (and enable on pre-production environments for testing)
Locally or on pre-prod environments Towns Fund round 5 should be active.
=> SMD-758: Update Fund config for Towns Fund round 5

app/const.py
=> Add wycombe email domain to LA lookup

app/const.py
Allow e-lindsey.gov.uk accounts to submit for Boston council as per support request.
=> BAU: Add Boston council returns perms for E-Lindsey

app/const.py
Add `cheshirewest.gov.uk` to list of `const`.
=> [BAU] Add cheshirewest domain

copilot/submit/manifest.yml
Switch on maintenance mode for all envs
=> FPASF-284: Switch on maintenance mode for all envs
