communitiesuk/funding-service-design-post-award-submit

TODO.md
app/static/src/css/custom.css
app/templates/base.html
app/templates/main/login.html

- Updates base.html so that the footer reflects the design
- Overwrites padding-top for main wrapper to prevent large white space between phase banner and content
Footer now corresponds to design specification on all pages, such as below:

[SMD-43]: update base html

---

app/static/src/css/custom.css

Fixes right-margin such that pages now have the same margins as designs in: https://www.figma.com/file/eU00tDFeRbGx4PCN1uFBHW/%2F%2F-Submit-%2F%2F-October-2023-TF-Deliverable?type=design&node-id=145-1674&mode=design&t=Vmyeo9rH6BURCdEW-0
Before:
After:

BAU: fix margins

---

app/main/routes.py
app/templates/main/errorAccordion.html
app/templates/main/success.html
app/templates/main/upload.html
config/envs/default.py
tests/test_routes.py

Currently all errors are raised on the back end, collated, and surfaced here. The code handles this by deliniating the status_code of thee responce then checking for any PreTransformationErrors and TabErrors contained in the responce body that need to be surfaced in one of three ways:
Three paths for error handling added:
- Happy path: Sucessfull upload
Status_code = 200
No errors returned. renders a seperate html page success.html where the user is informed of their success and they can log off the service
- Unhappy path 1: Pre validation errors
Status_code = 400
Error that stops spreedsheet ingestion from being attempted e.g wrong file type, Invalid tabs in the spreedsheet, or an invalid organisation name. Prompts user to re-upload
Renders on page using the file upload error message
- …

User friendly error presentation

---

app/main/data_requests.py
app/main/routes.py
app/templates/main/uncaughtValidation.html
config/envs/default.py
tests/test_routes.py

https://dluhcdigital.atlassian.net/jira/software/c/projects/SMD/boards/140?modal=detail&selectedIssue=SMD-80
Handle 500 errors from the data-store by displaying a page that prompts the user to contact FSD support to help with their submission. This occurs when there is an uncaught exception during ingest - which can happen for various reasons.

[SMD-80] handle 500 errors from the data-store

---

app/main/routes.py
app/templates/main/uncaughtValidation.html
app/templates/main/upload.html
tests/test_routes.py

Adds the changes from SMD-111: Modify existing uncaught error screen with a place holder error code
Also adds the changes from SMD-83: To show the message: "The selected file must be an Excel file when users atempt to upload a non Excel file

[SMD-111] Modify existing error screen for uncaught validation error

---

config/envs/development.py

Email domain for DLUHC users is actually communities.gov.uk in AD.
Should be able to authenticate locally if you have a communities/levellingup email.

BAU: fix email domain

---

app/main/authorisation.py
tests/test_authorisation.py

Whilst domain resolution is case-insensitive, our e-mail mappings were not. All e-mails now default to lower-case.

BAU: make email lookup case insensitive

---

app/main/routes.py
config/envs/default.py
config/envs/development.py
tests/conftest.py
tests/test_routes.py

Enforce user role membership to access upload route
* In docker runner: user should not be able to access upload route unless they are given the role. Ensure you have latest versions of authenticator and account-store for this to work
* I can add people to the role to test being able to access once role is added

SMD-173: enforce role membership

---

app/templates/main/upload.html

Fixes the width of the upload page 
- removes two duplicate tags that wrap upload template content. These tags were already produced by a base template component
Old width:
New width:
Figma width:

[BAU] remove duplicate wrapper in upload template

---

app/__init__.py
config/envs/default.py

Previously we were only getting system level logs through on AWS as we hadn't initialised the utils logging library.
Logs should come through in JSON format if the app is run in non-development environments

SMD-276: init logging from utils library

---

copilot/submit/manifest.yml

Bump NGINX max body size so uploads are not curtailed on the NGINX side. Should prevent 413 errors on large file uploads on the pre-prod environments
Should not fail with 413 when files over 1mb are uploaded

SMD-318: Bump NGINX max body size

---

app/templates/main/help-links.html
config/envs/default.py

https://dluhcdigital.atlassian.net/jira/software/c/projects/SMD/boards/140?quickFilter=815&selectedIssue=SMD-253
Adds a link to the helpdesk URL, added to help-links.html so users can access it either from the dropdown or after successfully submitting their return.
The link should be clickable from the front end, and can be changed in default.py.

add service desk URL to env vars

---

.github/workflows/deploy.yml

_Add ticket reference to Pull Request title: e.g. 'FS-123: Add content', if there is no ticket prefix with BAU_
Previously concurrency was across all deploys, concurrency should be per environment not global
Should not concurrency lock against other environment deployment

BAU: concurrency should be per environment not global

---

app/const.py

Added 4 new local authoritiy domains to our mapping that were sent over by towns fund, that we did not have already.
carlisle
portsmouthcc
chorley
corby

add additional local authorites for round 4

---

.github/workflows/deploy.yml
Procfile
README.md
copilot/submit/manifest.yml
project.toml

Switches deployed environments to use [packeto buildpack](https://paketo.io/)
N.B. the local Dockerfile is retained for local development only
Have deployed on dev environment https://github.com/communitiesuk/funding-service-design-post-award-submit/actions/runs/6772020403/job/18403679668

SMD-334: switch to paketo buildpack

---

app/main/routes.py
config/envs/default.py
requirements.in
requirements.txt
requirements_dev.txt
tests/test_routes.py

https://dluhcdigital.atlassian.net/jira/software/c/projects/SMD/boards/140?quickFilter=815&selectedIssue=SMD-346
Redirects the user to Submit's sign-in page at /login rather than the generic version hosted on Authenticator repo. In order for this to work, the related FSD Utils PR will need to be merged, and the relevant version number increased to reflect the changes.

Feature/smd 346/logged out content

---

app/const.py

https://dluhcdigital.atlassian.net/jira/software/c/projects/SMD/boards/140/backlog?selectedIssue=SMD-392
This PR updates the local authorities available for users under the Carlisle domain, as according to a support request which came through.

update LA mappings as Carlisle and Cumberland have merged

---

app/templates/base.html
app/templates/main/errorTable.html
app/templates/main/upload.html
app/templates/main/validation-errors.html
tests/test_routes.py

This PR addresses several formating/ content issues raised by design here: 
https://dluhcdigital.atlassian.net/wiki/spaces/FS/pages/50561200/Design+Team+testing
in order that they appear below they are:
- Header service name too small - 15px and missing class Fix: use serviceName attribute in govukHeader
- Tab and section data displaying in title case when should be sentance case Fix: use python capitalize to force sentance case
- First column of table not tagged and formatted as table header 
- “Upload your data return” field label should be tagged as label
- “There are errors in your return” should be h1 and govuk-heading-l
- “Re-upload your data return” should be label and govuk-heading-m
- We do not redisplay this message on the validation errors screen: "When you upload your return, …

[SMD-369] content and formating changes

---

app/templates/main/500.html
app/templates/main/login.html
app/templates/main/success.html
app/templates/main/upload.html
app/templates/main/validation-errors.html

https://dluhcdigital.atlassian.net/browse/SMD-348
- overrides the width of the error page to full
- overrides the width of the upload, login, success and 500 pages to two thirds

[SMD-348] override page widths

---

app/static/src/css/custom.css
app/templates/base.html

Fix a formating bug introduced in a previous PR
Also add a favicon and ensure file paths to static images are correct
Header
Footer
Favicon

fix header formating and justify sign out to the right

---

app/const.py
app/main/routes.py
config/envs/default.py
tests/test_routes.py

https://dluhcdigital.atlassian.net/jira/software/c/projects/SMD/boards/140?quickFilter=815&selectedIssue=SMD-361
Formats and displays pre-validation/validation errors for logging. Also implements a flag which can be turned off the disable this logging. I have not included any further information as to the error type from data-store, however this can be included if others think it will be beneficial.
I have updated the outdated key names from cell to cell_index in test_upload_xlsx_validation_errors. I have checked this is the expected name in the back end also.
The errors should be available in the Docker logs/terminal console when testing locally. The flag ENABLE_VALIDATION_LOGGING is set to True by default in config/default.py

format validation errors for logging and add flag to config

---

app/const.py

- Replaces comma with a dash in nottingham city centre place name so it isn't separated into two when the request is parsed.

[BAU] nottingham city centre place name to not include a comma

---

app/const.py

- adds legacy Buckinghamshire domain to auth mapping

[BAU] add legacy Buckinghamshire domain to auth mapping

---

app/main/routes.py
tests/test_routes.py

https://dluhcdigital.atlassian.net/jira/software/c/projects/SMD/boards/140?quickFilter=815&selectedIssue=SMD-383
Redirects previously unhandled errors (those not in the exisiting error templates) to the generic 500 error page, instead of creating an unhandled exception.

Smd 383/feature/additional http errors

---

app/const.py

Add mendip.gov.uk to the authenticated email domains with the same permissions as somerset.go.uk
As medip has recently merged into somerset

add mendip email domain

---

app/const.py

Added somersetwestandtaunton.gov.uk to auth mapping so that a user can submit for the same places as somerset.gov.uk

add somersetwestandtaunton.gov.uk to auth mapping

---

app/main/data_requests.py
app/main/routes.py
app/templates/main/upload.html
app/templates/main/validation-errors.html

This PR 
Refactor so we no longer return un-necesary success boolian. 
When a user goes to upload a file they will now only see .xlsx files that are on there machine instead of all types of files

Feature/[smd 151] show error state on errors screen

---

copilot/submit/overrides/README.md
copilot/submit/overrides/cfn.patches.yml

As part of: https://github.com/communitiesuk/funding-service-design-post-award-submit/pull/125 we found it would be useful to have logs going back a longer period. Extending the log retention period is the easiest way of doing this.
Can check retention period in AWS console following deployment

BAU: increase log retention period to 90 days

---

app/main/authorisation.py
app/main/decorators.py
app/main/routes.py
tests/test_routes.py

Previously, we checked to see if a user had multiple Azure AD roles, and if they did then they would be given 401.
This has been changed because users should be allowed to have multiple Azure AD roles, as long as there isn't more than one role relevant to Submit (Submit only supports a single fund per user at the moment).
This changes the authentication code to match this logic.

[BAU] ignore non-Submit roles during authentication

---

app/__init__.py
app/main/authorisation.py
app/main/decorators.py
app/main/fund.py
tests/test_authorisation.py
tests/test_fund.py

Previously, we checked a users roles against a set of roles linked to funds and raised an exception if they had more than 1 "relevant role" associated with a fund.
Instead, we now allow a user to have a set of roles associated with multiple funds as long as only **one** is active.
This change also removes some buggy code in the `check_roles` function that has now been removed in place of checking
the resulting funds instead.

[BAU] allow a user to be associated with multiple funds as long as only one is active

---

app/main/data_requests.py
tests/test_routes.py

Fix excel filename not being passed to ingest and add test to cover this behaviour and assert filename passed correctly in request.

BAU: Fix excel filename not being passed to ingest

---

config/envs/development.py

Overrides auth when running in development, using the existing override functionality in the `@login_required` decorator
When running locally, you should be able to access `/upload` without going through Microsoft auth

SMD-615: add debug user for local development

---

copilot/submit/manifest.yml

Previously we had basic auth on test but not dev, this adds basic auth on dev.
Basic auth should be enabled on the dev environment

BAU: add basic auth on dev

---

app/main/fund.py
app/main/routes.py

[SMD-650 - Pathfinders - enable confirmation emails on successful ingest](https://dluhcdigital.atlassian.net/browse/SMD-650)
Now that we have added the email address for Pathfinders to the AWS secrets, we can remove the conditional logic blocking email confirmation on Pathfinders spreadsheet ingest.

SMD-650 - Enable confirmation emails on upload for Pathfinders

---

config/envs/development.py

Adds Bolton Council and Wirral Council as local authorities devs can submit for the purposes of testing.

BAU: add extra local authorities devs can submit for pf

---

app/const.py

Prevents error [Unknown fund type id found: PF](https://funding-service-design-team-dl.sentry.io/issues/5106056990/?referrer=slack&notification_uuid=8675e922-9f16-4351-9c49-37cb06a27365&alert_rule_id=14718986&alert_type=issue) on PF spreadsheet ingest.

BAU - Add PF to FUND_TYPE_ID_TO_FRIENDLY_NAME mapping

---

config/envs/development.py

Fixes PF additional e-mail mappings for development.

BAU: fix dev auth mapping

---

app/main/fund.py
tests/test_routes.py

make Towns Fund Round 4 inactive (now all LAs have submitted)
* Towns Fund should not appear on dashboard (if user has Towns Fund role)
* `/upload/TF/4` should 401

SMD-758: make Towns Fund Round 4 inactive

---

config/envs/default.py
copilot/submit/manifest.yml

Enable Towns Fund round 5.
We'll test after deployed to production.

SMD-758 Enable Towns Fund round 5

---

.pre-commit-config.yaml
app/__init__.py
app/const.py
app/main/data_requests.py
app/main/decorators.py
app/main/notify.py
app/main/routes.py
app/utils.py
pyproject.toml
requirements-dev.in
requirements-dev.txt
setup.cfg
tests/test_routes.py

https://dluhcdigital.atlassian.net/browse/SMD-812
Stop eagerly formatting log messages, which ends up causing some log messages to be double-formatted. When the initial format is injecting a dictionary into the string, the second format (by fsd_utils.logging) can error because the dict looks like a format injection point, but is incorrectly structured.
I've also switched black+flake8+isort out for [ruff](https://docs.astral.sh/ruff/), which is a fast modern tool that combines a bunch of formatting and linting rules. One of these will raise linting issues for log call that have eagerly-formatted log lines.

Stop logging with eagerly-formatted strings

---

app/main/routes.py
config/envs/development.py

Ticket:
https://dluhcdigital.atlassian.net/browse/FMD-251
Description:
On submission passes user's account_id and email address to data-store/ingest. 
DEBUG_USER_ACCOUNT_ID is added to config/envs/development.py to be able to test locally.

Persist submitting user metadata

---

app/templates/main/dashboard.html
app/templates/main/upload.html
app/templates/main/validation-errors.html
tests/test_routes.py

https://dluhcdigital.atlassian.net/jira/software/c/projects/SMD/boards/140?quickFilter=815&selectedIssue=SMD-697
Adds ID to certain front end elements for use in automated testing. They should be visible using inspect element on the front end.

[SMD-697] ID tags for testing

---

requirements-dev.txt
requirements.in
requirements.txt

Pull in latest fsd_utils, so that we can use the latest version of sentry.

Pull in latest fsd_utils and upgrade sentry

---

app/__init__.py
app/templates/main/maintenance-mode.html
config/envs/default.py

Adds a maintenance mode page to the app.

Add maintenance mode page

---

app/const.py

Adds `bromsgroveandredditch.gov.uk` to the `DOMAIN_TO_LA_PLACES` mapping, as per TF support request.

BAU: Add new email domain to LA mapping
